name: team_workspace_app
description: "Team Workspace App - Flutter Machine Test (Clean Architecture + Bloc)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.7.0

  # Networking
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3

  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5

  # Local persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0
  dartz: ^0.10.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
